services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    depends_on:
      - postgresdb
    build: ./backend-pdfs
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT_BACKEND:$PORT_BACKEND
    stdin_open: true
    tty: true
  angular-app:
    depends_on:
      - app
    build: 
      context: .
      dockerfile: frontend-pdfs/Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro # Certificados SSL
volumes: 
  db: